# Generated by Django 4.0.6 on 2022-07-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmartApp', '0003_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='size',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
