# Generated by Django 4.0.6 on 2022-07-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmartApp', '0007_alter_cart_item_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
