# Generated by Django 4.0.6 on 2022-07-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmartApp', '0008_alter_cart_item_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
