# Generated by Django 4.0.6 on 2022-07-29 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmartApp', '0009_alter_cart_item_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hmartApp.brand'),
            preserve_default=False,
        ),
    ]
