# Generated by Django 4.0.6 on 2022-08-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmartApp', '0011_alter_cart_item_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
