# Generated by Django 4.0.6 on 2022-08-04 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmartApp', '0012_alter_cart_item_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=0)),
                ('start_date_discount', models.DateTimeField(auto_now_add=True)),
                ('end_date_discount', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmartApp.product')),
            ],
        ),
    ]
